service: dio-aws-bootcamp
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:scan
      Resource: arn:aws:dynamodb:sa-east-1:850940624433:table/Item 

functions:
  insertItem:
    handler: src/item.handler
    events:
      - http:
          path: /item
          method: post
  updateItem:
    handler: src/item.handler
    events:
      - http:
          path: /item/{id}
          method: put
  getItens:
    handler: src/item.handler
    events:
      - http:
          path: /item
          method: get
  getItem:
    handler: src/item.handler
    events:
      - http:
          path: /item/{id}
          method: get
          
resources:
  Resources:
    Item:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: Item
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH